### PR TITLE
Improve Documentation

### PR DESCRIPTION
**Pull request by elkuku**
This will add links for all packages and sub packages to the corresponding documentation on GitHub.
The text is generated by some PHP code (included) that also checks if all files contain a documentation link.

### CODE REVIEW

**Comment by javigomez** [comment]
:+1:

**Comment by elkuku** [comment]
TBH I'd like to suggest removing all the "specific" sample code leaving only the sample on how to access the GitHub object.

Since the samples are incomplete, I believe we should refer only to the GitHub API reference with the links provided in this PR.

**Comment by mbabker** [comment]
Those examples could be moved into a more detailed documentation page, but I agree they probably aren't best located in the README.

**Comment by elkuku** [comment]
> Those examples could be moved into a more detailed documentation page, but I agree they probably aren't best located in the README.

Do we really want to compete with the GitHub API documentation?

A complete API implementation should be honored by a complete documentation :wink:

**Comment by mbabker** [comment]
Not necessarily competing with their docs, but making sure it's documented how you use our package.

**Comment by dongilbert** [comment]
> Not necessarily competing with their docs, but making sure it's documented how you use our package.

Exactly this. The GitHub API docs are great, but they don't explain how to use our PHP GitHub API package.

**Comment by elkuku** [comment]
> how to use our PHP GitHub API package.

That's why I would propose a "general example" on how to access the PHP GitHub API object - as already contained in [#instantiating-github](https://github.com/joomla-framework/github-api#instantiating-github) and remove the sample codes in [accessing-the-github-apis](https://github.com/joomla-framework/github-api#accessing-the-github-apis) which actually documents how to access a PHP method - information that is already contained in the doc blocks.

Maybe we can just keep some of them in a "Examples" section? Those using parameters and might actually "do" something?

I guess the README is just to long and looks like an intend to document our API implementation but unfortunately has been left incomplete so one might think that our whole stuff is incomplete - and that's just not true :wink:

**Comment by mbabker** [comment]
That's why one of the to-be-announced roadmap items is a focus on improving docs as a whole.  READMEs, while convenient, shouldn't be the primary documentation resource for a package.

**Comment by elkuku** [comment]
I am going to submit a PR for the changes I'd like to see to the README and we might discuss then, since this PR is only about adding information and not removing anything at all :wink:

**Comment by mbabker** [comment]
OK so in general the way we're moving with package docs can be seen in the [Language repo](https://github.com/joomla-framework/language) and [this pull in the HTTP repo](https://github.com/joomla-framework/http/pull/15).  I think for the links to the GitHub docs pages we'd put that in a `docs/references.md` file while starting to craft docs explaining how to use our API connector to fetch data from them.  Thoughts?

**Comment by elkuku** [comment]
> Thoughts?

No more thoughts.

**Pull request closed without merging**
