### PR TITLE
Use HTTP package exception on errors

### PR DESCRIPTION
**Pull request by mbabker**
Changes the `processResponse()` method to throw a [UnexpectedResponseException](https://github.com/joomla-framework/http/blob/master/src/Exception/UnexpectedResponseException.php) (provided by the HTTP package) which allows the full Response object to be attached to the exception for debugging purposes.

Standardizes all code (as able) to use `processResponse()` versus the internal checks that existed before this method was implemented.

Minor doc block standardizing.

### CODE REVIEW

**Comment by elkuku** [comment]
Sorry but I didn't found anything to moan about...

I'd push that merge button if I had one...

**Comment by wilsonge** [comment]
Conflicts :)

**Comment by mbabker** [comment]
Fixed

**Comment by mbabker** [comment]
Don't mind the test failures, they came from master because I forgot to add the new assignees data to those cases.  It's already fixed there.

**Pull request merged**
