### PR TITLE
Make a choice between assignees and assignee

### PR DESCRIPTION
**Pull request by jbanety**
Pull Request for Issue #35 

### Summary of Changes

We have to do a choice between assignees and assignee

### CODE REVIEW

**Comment by elkuku** [comment]
First of all let me say that I'm surprised since we are using this method currently in our issue tracker application.
Could you supply some (more or less) *real* data for the function call?

However the error makes perfect sense so there is definitely something that needs to get fixed.

I think it would make sense to check both values in the function first before submitting the data like 
```php
if (is_string($assignee) && !empty($assignees)) 
{
    throw new \UnexpectedValueException('You cannot pass both assignee and assignees. Only one may be provided.');
}
```
currently you are silently ignoring `$assignee` if `$assignees` is set.

And, well, the unit tests need some adjustment...

Anyway big :+1: for spotting this.

**Comment by jbanety** [comment]
Hi,
I created a PHP script to init new GitHub repo for new project.
It creates labels, issue templates and issues (to use with ZenHub for project management).

I don't want to assign the issue to somebody.

My code looks like : 

`issues.json`
```json
[
  {
    "title": "My Issue Title",
    "body": "My Issue Body",
    "labels": ["label1", "label2"]
  }
]
```

`create_issues.php`
```php
$options = new \Joomla\Registry\Registry;
$options->set('gh.token', $github_token);

$github = new \Joomla\Github\Github($options);
$issues = json_decode(file_get_contents(__DIR__.'/issues.json'));

foreach ($issues AS $issue) {
    try {
        $github->issues->create($github_owner, $github_repo, $issue->title, $issue->body, null, null, $issue->labels, []);
    } catch (\Exception $e) {
        die($e->getCode() . " : " . $e->getMessage());
    }
}
```

**Comment by mbabker** [comment]
That part's fine.  The problem @elkuku is pointing out though is that we are basically silently discarding the string `$assignee` in favor of the `$assignees` array and his suggestion is to instead check for the presence of both and raise an Exception telling the user they've passed an invalid data set.  So even if you aren't assigning items to users it would still be OK, we'd only be raising an alert if you passed non-empty values to both of those params.

**Comment by jbanety** [comment]
I added the parameters check to the PR.

**Comment by elkuku** [comment]
That was faster than @jbanety merging jbanety/github-api#2 :wink: Thanks!

**Pull request merged**
